# Keyboard / pointer / touchpad config.
# Docs: https://wiki.hyprland.org/Configuring/Variables/#input
#
# Change kb_layout to your locale (de, gb, fr, etc).
# Run `localectl list-x11-keymap-layouts` for the full list.

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    sensitivity = 0
    follow_mouse = true
    natural_scroll = true
    force_no_accel = true

    touchpad {
        natural_scroll = true
        clickfinger_behavior = 1
    }
}
