-- Hyprland monitor configuration
-- Docs: https://wiki.hypr.land/Configuring/Basics/Monitors/
--
-- Format: hl.monitor({ output = "NAME", mode = "RESOLUTION@REFRESH", position = "POS", scale = N })
-- Find your monitor names with: hyprctl monitors
--
-- Examples:
--   hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0", scale = 1 })
--   hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@144", position = "1920x0", scale = 1 })
--   hl.monitor({ output = "DP-1", mode = "preferred", position = "auto", scale = 1 })
--
-- Fallback for any unspecified monitor:
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
